steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/boatrace-ai', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/boatrace-ai']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
    - 'run'
    - 'deploy'
    - 'bortrace-ai-api'
    - '--image'
    - 'gcr.io/$PROJECT_ID/boatrace-ai'
    - '--region'
    - 'asia-northeast1'
    - '--platform'
    - 'managed'

options:
  logging: CLOUD_LOGGING_ONLY